apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.namespace.name }}
data:
  SERVICE_NAME: {{ .Values.app.name | quote }}
  ENVIRONMENT_NAME: {{ .Values.app.environment | quote }}
  PLATFORM_TEAM: {{ .Values.service.team | quote }}
  DEPLOYMENT_VERSION: {{ .Chart.AppVersion | quote }}
  DEPLOYMENT_TAG: {{ .Values.backend.image.tag | quote }}
  DEPLOYMENT_BUILD_DATE: {{ .Values.service.buildDate | quote }}
  DB_HOST: {{ .Values.app.name }}-postgres
  DB_PORT: {{ .Values.postgresql.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  PORT: {{ .Values.backend.port | quote }}
